# Exercise 3- Bayesian Networks and the Darwiche Compiler

In this exercise, we will learn the parameters of a Bayesian Network and perform inference. 
We will then compare our results to those of the Darwiche compiler.

In the event of a persistent problem, do not hesitate to contact the course instructors under
- paul.kahlmeyer@uni-jena.de

### Submission

- Deadline of submission:
        13.11.2022
- Submission on [moodle page](https://moodle.uni-jena.de/course/view.php?id=34630)

### Help
In case you cannot solve a task, you can use the saved values within the `help` directory:
- Load arrays with [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.load.html)
```
np.load('help/array_name.npy')
```
- Load functions, classes and other objects with [Dill](https://dill.readthedocs.io/en/latest/dill.html)
```
import dill
with open('help/some_func.pkl', 'rb') as f:
    func = dill.load(f)
```

to continue working on the other tasks.

# Bayesian Networks

## Dataset
In this exercise we will used a discretized version of the [Pima Indians Dataset](https://www.kaggle.com/uciml/pima-indians-diabetes-database/version/1). In its original form, nine attributes were collected:

- `Pregnancies` : Number of times pregnant 
- `Glucose` : Plasma glucose concentration a 2 hours in an oral glucose tolerance test
- `BloodPressure` : Diastolic blood pressure (mm Hg)
- `SkinThickness` : Triceps skin fold thickness (mm)
- `Insulin` : 2-Hour serum insulin (mu U/ml)
- `BMI` : Body mass index (weight in kg/(height in m)^2)
- `DiabetesPedigreeFunction` : Value indicating the presence of diabetes in the family
- `Age` : Age
- `Outcome`:  1- Diabetes, 0- No diabetes

For this exercise, we will use a binarized version of this dataset. Each attribute has been labeled
- `0` below average
- `1` above average

The dataset is stored as `dataset.csv`. 


### Task 1
Load the dataset.

In [1]:
# TODO: load dataset
import numpy as np
import pandas as pd
from enum import Enum
data = pd.read_csv("dataset.csv").to_numpy()

class Columns(Enum):
    Pregnancies = 0
    Glucose = 1
    BloodPressure = 2
    SkinThickness = 3
    Insulin = 4
    BMI = 5
    DiabetesPedigreeFunction = 6
    Age = 7
    Outcome = 8

## Binary Bayesnet

A Bayesian network is a multivariate categorical where certain conditional independencies hold that are specified by a directed acyclic graph (DAG) on the variables.
Namely, any variable $x_i$ is conditionally independent from its non-descendants given the values of its parents.
This means that the joint distribution factorizes over each node given its parents.

Consider the following example of three variables:

<div>
<img src="images/bayesnet_example.png" width="200"/>
</div>

Here we have that 
\begin{equation}
p(x_0, x_1, x_2) = p(x_0)p(x_2|x_0)p(x_1|x_0,x_2)
\end{equation}

Such a categorical distribution can be represented by **Conditional Probability Tables** (CPTs), that hold the distributions $p(x_i| \text{parents}(x_i))$. 

In our example we would have three CPTs:

| $x_0$ | $p(x_0)$|
| :- | -: | 
| $0$ | $p(x_0=0)$|
| $1$ | $p(x_0=1)$|

| $x_0$ | $x_2$| $p(x_2|x_0)$|
| :- | :- | -: | 
| $0$ | $0$ | $p(x_2=0|x_0=0)$ | 
| $0$ | $1$ | $p(x_2=1|x_0=0)$ | 
| $1$ | $0$ | $p(x_2=0|x_0=1)$ | 
| $1$ | $1$ | $p(x_2=1|x_0=1)$ | 

| $x_0$ | $x_2$| $x_1$| $p(x_1|x_0, x_2)$|
| :- | :- | :- | -: | 
| $0$ | $0$ | $0$ | $p(x_1=0|x_0=0, x_2=0)$ | 
| $0$ | $0$ | $1$ | $p(x_1=0|x_0=0, x_2=1)$ | 
| $0$ | $1$ | $0$ | $p(x_1=0|x_0=1, x_2=0)$ | 
| $0$ | $1$ | $1$ | $p(x_1=0|x_0=1, x_2=1)$ | 
| $1$ | $0$ | $0$ | $p(x_1=1|x_0=0, x_2=0)$ | 
| $1$ | $0$ | $1$ | $p(x_1=1|x_0=0, x_2=1)$ | 
| $1$ | $1$ | $0$ | $p(x_1=1|x_0=1, x_2=0)$ | 
| $1$ | $1$ | $1$ | $p(x_1=1|x_0=1, x_2=1)$ | 


### Task 2

For our dataset, we have the adjacency matrix of such a DAG stored in `adj.npy`.

An entry $A_{ij}$ is 1, if there is an edge from $x_i$ to $x_j$. 

Load and display the adjacency matrix.

In [2]:
# TODO: load and display adjacency matrix
adj = np.load("adj.npy")

### Task 3

Implement the following `BinaryBayeNet` class.

Then create and fit a Bayesnet on the Diabetes dataset and calculate the [loglikelihood](https://en.wikipedia.org/wiki/Likelihood_function).

In [3]:
import itertools
from typing import Self


class BinaryBayesNet:

    def __init__(self, A: np.ndarray, prob_tables: dict[int, tuple[np.ndarray, np.ndarray, np.ndarray]] = {}) -> None:
        '''
        Bayesian Network of binary categorical variables.

        @Params:
            A...            adjacency matrix of the DAG
            prob_tables...  probability tables of the nodes, dictionary where
                            key = node index
                            value = tuple (sample space, probs, indices of sample space)
                            .fit(X) will estimate those prob_tables
        '''
        self.A = A
        self.n = self.A.shape[0]
        self.domain = [0, 1]
        self.prob_tables = prob_tables
        self.sample_space = np.array(list(itertools.product(self.domain, repeat=self.n)))

    def fit(self, dataset: np.ndarray, pseudo_obs: int = 0) -> Self:
        '''
        Calculates the CPTs for the Bayesian Network.

        @Params:
            dataset... Nxd matrix, binary vectors as rows
            pseudo_obs... pseudo observations that are added for laplace regularization
        '''

        self.prob_tables = {}
        for i in range(self.n):
            # make prob table for i
            parents = self.parents(i)
            # marginalize on i and parents
            marg = dataset[:, [i] + parents]
            # sample space for the parents
            parents_sample_space = np.array(list(itertools.product(self.domain, repeat=len(parents))))
            # build prob_table
            probs = np.empty(len(parents_sample_space))
            for entry_index, parents_entry in enumerate(parents_sample_space):
                # condition on parents
                fit_condition = np.all(marg[:, 1:] == parents_entry, axis=1)
                cond = marg[fit_condition, 0]
                total = len(cond)
                # count how many 1s and 0s are in conditioned data set
                ones_count = np.count_nonzero(cond)
                zero_count = len(cond) - ones_count
                # laplace regularization adds each sample c times. This is c * 2^(n - k) entries where k is the number of set indices (k = 1 + len(parents)).
                laplace_amount = pseudo_obs * 2**(self.n - len(parents) - 1)
                # 1 index less is set if i is not set, but the parents still are
                # p(x_i = 0 | x_pa(i) = parents_entry)
                probs[entry_index] = (zero_count + laplace_amount) / (total + 2 * laplace_amount)
            self.prob_tables[i] = (parents_sample_space, probs, parents)
        return self

    def proba(self, X: np.ndarray) -> np.ndarray:
        '''
        Calculates the probabilities of samples X.

        @Params:
            X... numpy array with samples as rows

        @Returns:
            numpy array with p(x)
        '''

        return np.array([self.single_prob(x) for x in X])

    def single_prob(self, x: np.ndarray) -> np.floating:
        # self.prob_tables[i][0] has the sample space, self.prob_tables[i][2] has the parent indices of i
        # np.where(np.all(self.prob_tables[i][0] == x[self.prob_tables[i][2]], axis=1))[0][0] is the index of the entry of the observed parents
        find_entry = lambda i: np.where(np.all(self.prob_tables[i][0] == x[self.prob_tables[i][2]], axis=1))[0][0]
        # p(x_i = 0 | x_pa(i)) for all indices
        prob_0s = np.array([self.prob_tables[i][1][find_entry(i)] for i in range(self.n)])
        # p(x) = x * p_0 + (1 - x) * (1 - p_0)
        return np.prod(x * prob_0s + (1 - x) * (1 - prob_0s))

    def parents(self, node: int) -> list[int]:
        return list(np.argwhere(self.A[:, node] == 1)[:, 0])


# TODO: fit Bayesian Network + calculate loglikelihood
bayesnet: BinaryBayesNet = BinaryBayesNet(adj).fit(data)
likelyhood = bayesnet.proba(data)


### Task 4

Use the bayesian network to answer the following queries:

1. What is the posterior marginal distribution of `Diabetes` if we observe a high `BMI` and a high `Glucose` level?
2. What is the prior marginal distribution of `Pregnancies` and `Glucose`?
3. What is the MAP hypothesis of `Age` given a high `BloodPressure`?

In [4]:
# TODO: answer inference queries
import utils
prob_table = np.c_[bayesnet.sample_space, bayesnet.proba(bayesnet.sample_space)]
task_1 = utils.posterior_marginal(prob_table, [Columns.Outcome.value], [Columns.BMI.value, Columns.Glucose.value], [1, 1])
task_2 = utils.prior_marginal(prob_table, [Columns.Pregnancies.value, Columns.Glucose.value])
task_3 = utils.max_a_posteriori(prob_table, [Columns.Age.value], [Columns.BloodPressure.value], [1])
print(f"task_1:\n{task_1}\ntask_2:\n{task_2}\ntask_3:\n{task_3}")

[1, 1]
[1]
task_1:
[[0.         0.68899732]
 [1.         0.31100268]]
task_2:
[[0.         0.         0.3114246 ]
 [0.         1.         0.25682388]
 [1.         0.         0.26939603]
 [1.         1.         0.16235549]]
task_3:
[0.]


# Darwiche Compiler

The [Darwiche Compiler](http://reasoning.cs.ucla.edu/c2d/) compiles a logical CNF formula into an arithmetic circuit.

For our bayesian network, we can create the CNF out of the network polynomial and compile it using the `utils.to_circuit` function.

With the following tasks we will create this CNF step-by-step.

## State Monomials

First we need monomials of the form $\theta_{i:z_i}$ that are true if node $i$ takes the value $z_i$.


### Task 5
Create a dictionary, which holds these monomials in the format
- key = monomial index, an ID for the monomial
- value = tuple (node index, node value).

Example: 
```
6 : (2, 1)
```
stands for the monomial $\theta_{2:1}$ which we name with index 6.

*Important:*

Later we want to encode a negative index as the negation of the monomial. Therefore we need to **start counting at 1** (so that we have a different negative value).


In [5]:
# TODO: create monomials
domain = [0, 1]
monomials = {i: (node, value) for i, (node, value) in enumerate(itertools.product(range(bayesnet.n), domain), 1)}
monomials_inverted = {(node, value): i for i, (node, value) in enumerate(itertools.product(range(bayesnet.n), domain), 1)}
monomials


{1: (0, 0),
 2: (0, 1),
 3: (1, 0),
 4: (1, 1),
 5: (2, 0),
 6: (2, 1),
 7: (3, 0),
 8: (3, 1),
 9: (4, 0),
 10: (4, 1),
 11: (5, 0),
 12: (5, 1),
 13: (6, 0),
 14: (6, 1),
 15: (7, 0),
 16: (7, 1),
 17: (8, 0),
 18: (8, 1)}

## Conditional Monomials
Next we need monomials of the form $\theta_{i, pa(i): z_i, z_{pa(i)}}$, that are true if node $i$ takes the value $z_i$ and the parent nodes of $i$, namely $pa(i)$ take the values $z_{pa(i)}$.

### Task 6
Create a dictionary, which holds these monomials and their probability in the format
- key = monomial index, an ID for the monomial
- value = tuple (probability, tuple of tuples (node idx, node value)).

Example:

```
24 : (0.3, ((8, 0), (1, 1)))
```

stands for the monomial $\theta_{1, 8 : 1, 0}$ with the probability $p(x_1=1|x_8=0) = 0.3$ which we name with index 24.

*Important:*

In order for the compiler to work, the tuple of tuples **first has to specify the parents and then the actual node**.

In [6]:
# TODO: create monomials
parents = [bayesnet.parents(node) for node in range(bayesnet.n)]
# sample spaces for node + parents
# assigns an element of a sample space to a number of variables (makes a tuple)
assign = lambda node, entry: tuple(zip((parents[node] + [node]), entry))
# gets the probability of and index in the probability table
prob = lambda node, entry_index: bayesnet.prob_tables[node][1][entry_index]
# collect conditional monomials where node = 0 and where node = 1
cond_monomials_list_0 = [(prob(node, entry_index), assign(node, list(prob_table_entry) + [0])) for node in range(bayesnet.n) for entry_index, prob_table_entry in enumerate(bayesnet.prob_tables[node][0])]
cond_monomials_list_1 = [(1 - prob(node, entry_index), assign(node, list(prob_table_entry) + [1])) for node in range(bayesnet.n) for entry_index, prob_table_entry in enumerate(bayesnet.prob_tables[node][0])]
# 0s are odd indices, 1s are even indices
cond_monomials_0 = {2 * i - 1: cond_monomial for i, cond_monomial in enumerate(cond_monomials_list_0, len(monomials) // 2 + 1)}
cond_monomials_1 = {2 * i: cond_monomial for i, cond_monomial in enumerate(cond_monomials_list_1, len(monomials) // 2 + 1)}
# merge the dicts
cond_monomials = cond_monomials_0 | cond_monomials_1
cond_monomials_inverted = {cond_monomials[key]: key for key in cond_monomials.keys()}
cond_monomials


{19: (0.7658227848101266, ((7, 0), (0, 0))),
 21: (0.20748299319727892, ((7, 1), (0, 0))),
 23: (0.692, ((8, 0), (1, 0))),
 25: (0.27238805970149255, ((8, 1), (1, 0))),
 27: (0.6075949367088608, ((1, 0), (5, 0), (2, 0))),
 29: (0.3791208791208791, ((1, 0), (5, 1), (2, 0))),
 31: (0.35294117647058826, ((1, 1), (5, 0), (2, 0))),
 33: (0.2676056338028169, ((1, 1), (5, 1), (2, 0))),
 35: (0.45703125, ((3, 0),)),
 37: (0.8571428571428571, ((1, 0), (3, 0), (4, 0))),
 39: (0.6111111111111112, ((1, 0), (3, 1), (4, 0))),
 41: (0.8040540540540541, ((1, 1), (3, 0), (4, 0))),
 43: (0.26865671641791045, ((1, 1), (3, 1), (4, 0))),
 45: (0.6894586894586895, ((3, 0), (5, 0))),
 47: (0.31414868105515587, ((3, 1), (5, 0))),
 49: (0.6784968684759917, ((4, 0), (6, 0))),
 51: (0.5121107266435986, ((4, 1), (6, 0))),
 53: (0.8577586206896551, ((2, 0), (8, 0), (7, 0))),
 55: (0.627906976744186, ((2, 0), (8, 1), (7, 0))),
 57: (0.5708955223880597, ((2, 1), (8, 0), (7, 0))),
 59: (0.37362637362637363, ((2, 1), 

## CNF of the network polynomial

Let $\theta_{I:Z}$ be the monomial that stands for the node indices $I$ being set to values $Z$.
Then the CNF of the network polynomial is made from the following disjunctions:

1. For each node $i$
    - $\theta_{i:0}\vee\theta_{i:1}$
    - $\neg\theta_{i:0}\vee\neg\theta_{i:1}$
  
2. For each combination of a node $i$ and its parents $pa(i)$
    - $\neg\theta_{i,pa(i) : z_i, z_{pa(i)}}\vee\theta_{i:z_i}$
    - $\neg\theta_{i,pa(i) : z_i, z_{pa(i)}}\vee\theta_{j:z_j}$ for each $j\in pa(i)$
    - $\theta_{i,pa(i) : z_i, z_{pa(i)}}\vee\neg\theta_{i:z_i}\vee\bigvee_{j\in pa(i)}\neg\theta_{j:z_j}$
    

### Task 7

Create the CNF as a list of lists, where each list represents a disjunction with the monomial indices (negative indices stand for negated monomials).

Example:

```
[[1 , 2], [-5 , -6]]
```
would stand for the CNF

$\left(\theta_1\vee\theta_2\right) \wedge \left(\neg\theta_5\vee\neg\theta_6\right)$.

In [7]:
# TODO: create CNF list
cnf = []
# not 0 => 1
cnf += [[2 * i - 1, 2 * i] for i in range(1, bayesnet.n + 1)]
# 0 => not 1
cnf += [[-(2 * i - 1), -2 * i] for i in range(1, bayesnet.n + 1)]
# node monomial is the last entry of the second tuple entry
node_index = lambda cond_monomial: monomials_inverted[cond_monomial[1][-1]]
# parent monomials are firtst entries of the second tuple entry
parent_indices = lambda cond_monomial: [monomials_inverted[parent] for parent in cond_monomial[1][:-1]]
# negate every literal in that list
negate = lambda index_list: [-index for index in index_list]
# cond => node
cnf += [[-cond_monomial_index, node_index(cond_monomial)] for cond_monomial_index, cond_monomial in cond_monomials.items()]
# cond => parent
cnf += [[-cond_monomial_index, parent_index] for cond_monomial_index, cond_monomial in cond_monomials.items() for parent_index in parent_indices(cond_monomial)]
# parents => cond
cnf += [[-cond_monomial_index] + negate(parent_indices(cond_monomial)) for cond_monomial_index, cond_monomial in cond_monomials.items()]
cnf


[[1, 2],
 [3, 4],
 [5, 6],
 [7, 8],
 [9, 10],
 [11, 12],
 [13, 14],
 [15, 16],
 [17, 18],
 [-1, -2],
 [-3, -4],
 [-5, -6],
 [-7, -8],
 [-9, -10],
 [-11, -12],
 [-13, -14],
 [-15, -16],
 [-17, -18],
 [-19, 1],
 [-21, 1],
 [-23, 3],
 [-25, 3],
 [-27, 5],
 [-29, 5],
 [-31, 5],
 [-33, 5],
 [-35, 7],
 [-37, 9],
 [-39, 9],
 [-41, 9],
 [-43, 9],
 [-45, 11],
 [-47, 11],
 [-49, 13],
 [-51, 13],
 [-53, 15],
 [-55, 15],
 [-57, 15],
 [-59, 15],
 [-61, 17],
 [-63, 17],
 [-20, 2],
 [-22, 2],
 [-24, 4],
 [-26, 4],
 [-28, 6],
 [-30, 6],
 [-32, 6],
 [-34, 6],
 [-36, 8],
 [-38, 10],
 [-40, 10],
 [-42, 10],
 [-44, 10],
 [-46, 12],
 [-48, 12],
 [-50, 14],
 [-52, 14],
 [-54, 16],
 [-56, 16],
 [-58, 16],
 [-60, 16],
 [-62, 18],
 [-64, 18],
 [-19, 15],
 [-21, 16],
 [-23, 17],
 [-25, 18],
 [-27, 3],
 [-27, 11],
 [-29, 3],
 [-29, 12],
 [-31, 4],
 [-31, 11],
 [-33, 4],
 [-33, 12],
 [-37, 3],
 [-37, 7],
 [-39, 3],
 [-39, 8],
 [-41, 4],
 [-41, 7],
 [-43, 4],
 [-43, 8],
 [-45, 7],
 [-47, 8],
 [-49, 9],
 [-51, 10],

### Task 8

Use the `utils.to_circuit` function to compile the CNF into an arithmetic circuit.

As a sanity check compare the probabilities of the arithmetic circuit that you obtain with `.eval` to those of your Bayesnet.

*Note:* `.eval` takes $x\in\mathbb{R}^n$ and outputs $p(x)$.

In [17]:
# TODO: convert into arithmetic circuit
# NOTE: this was for debugging purposes
with open("bruh.txt", 'w') as f:
    f.write(f"n = {bayesnet.n}\nmonomials = {str(monomials)}\ncond_monomials = {str(cond_monomials)}\ncnf = {str(cnf)}")
# NOTE: idk, it can't find existing files and it can't open files it should be able to open.
circuit = utils.to_circuit(bayesnet.n, monomials, cond_monomials, cnf)

# TODO: sanity check - are probabilities correct?

Error during compilation process: 
Constructing CNF... DONE
CNF stats: 
  Vars=64 / Clauses=178
  CNF Time	0.000s
Constructing vtree (from primal graph)...Cannot open dtree file: htree_12042.tmp



sh: 1: /home/user/stuff/uni/ws_22_23/GM-LAB/exercise03/compiler/util/c2d/hgr2htree: not found


CalledProcessError: Command '['compiler/util/c2d/miniC2D', '-c', 'tmp/nnf/graphical_model.cnf']' returned non-zero exit status 1.